name: Deploy

on: 
  workflow_run:
    workflows: [Test]
    branches: [feature/resume-content]
    types: 
      - completed
      
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          yarn install
          yarn build
    
#  deploy:
#    runs-on: macos-latest
#    needs: build
#    steps:
#      - uses: jakejarvis/s3-sync-action@v0.5.1
#        with:
#          args: --acl public-read --follow-symlinks --delete
#        env:
#          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}  
#          SOURCE_DIR: 'build'
